### ISSUE TITLE
Authentication setup

### ISSUE THREAD

**Issue by BackwardsNode** [Durhack2022-2-Go-Green/go-green-server#4]
Need to implement and test user authentication.

- We will use JWTs
- Express middleware
- Used as identifier for certain endpoints
- Test user storage
    - Make sure passwords are stored as bcrypt hashes and enforced
    - Prevent duplicate usernames
- Support for email?

**Comment by WillMW02** [comment]
Complete with exception of email, Could implement email if desired.
